### ISSUE TITLE
setting font

### ISSUE THREAD

**Issue by rimmesbe** [jessorellanes/prj-rev-bwfs-dasmoto#2]
This works but if this was a real sized project it would be a hassle to have to list every tag we want to have this font. Instead set the default font for the page with inheritance:
html { font-family: Helvetica, sans-serif; }
Now all elements will inherit this font default.

https://github.com/jessorellanes/prj-rev-bwfs-dasmoto/blob/master/Dasmoto/resources/css/style.css#L1-L6

**Comment by jesspetrillo** [comment]
Sure! Absolutely logical. Thanks.
