### ISSUE TITLE
bold styling

### ISSUE THREAD

**Issue by rimmesbe** [jessorellanes/prj-rev-bwfs-dasmoto#3]
You will very rarely need to add the style for bold in css because many elements come with it default. Bold usually is used to show importance, so you should use a tag that semantically represents that in the html like header tags which default to bold and strong tags which are like span tags that default to bold and add some semantic weight.

https://github.com/jessorellanes/prj-rev-bwfs-dasmoto/blob/master/Dasmoto/resources/css/style.css#L8-L13

**Comment by jesspetrillo** [comment]
Got it. It didn't occurred to me that headers were bold by default. Thanks a lot. This code reviews are great.
