### ISSUE TITLE
good place for a class

### ISSUE THREAD

**Issue by rimmesbe** [jessorellanes/prj-rev-bwfs-dasmoto#4]
This would be a good candidate for a class. We want to keep the span element as un-styled by default as possible incase we need to use it elsewhere later on. Using a class here preserves the span tag and adds some description to the component we are styling:
.price { color: blue; }

https://github.com/jessorellanes/prj-rev-bwfs-dasmoto/blob/master/Dasmoto/resources/css/style.css#L39-L41

**Comment by jesspetrillo** [comment]
Cool. Thanks.
