### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by rimmesbe** [jessorellanes/prj-rev-bwfs-dasmoto#5]
Grade: Exceeds expectations 

Summary: Very nice job on this project, the end result looks great. Your html was perfect, and your css was perfectly fine for this particular project. I created a few issues with some tweaks that will help you as projects grow in size and it is more important to use the most efficient and organized techniques. Well done, you are ready for the next sections.

**Comment by jesspetrillo** [comment]
As I shared in Slack, these reviews are awesome! 
The feedback I received was very detailed with clear explanations and actionable advice to improve my work. I'm very happy.

**Comment by rimmesbe** [comment]
My pleasure. Thanks for sharing.

On Mon, Aug 28, 2017 at 3:07 PM, Jessica Orellanes <notifications@github.com
